[tool.black]
line-length = 90
target-version = ["py37", "py38", "py39"]
extend-exclude = """
/(
  | .*/migrations
  | tests/data
)/
"""
[tool.isort]
py_version = "38"
profile = "black"
line_length = 90
force_single_line = true
lines_after_imports = 2
skip_gitignore = true
atomic = true
honor_noqa = true
remove_redundant_aliases = true
src_paths = "."
extend_skip_glob = ["*/migrations/*"]