# Generated by Django 3.2.16 on 2022-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=1),
        ),
    ]
