# Generated by Django 3.2.16 on 2022-12-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stays', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=500),
        ),
    ]
