# Generated by Django 3.2.16 on 2022-11-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Cami', max_length=20)),
                ('email', models.EmailField(default='cami@gmail.com', max_length=254)),
                ('phone', models.PositiveIntegerField(default=893929393)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'person',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.person'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Hugo', max_length=20)),
                (
                    'person',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.person'),
                ),
            ],
        ),
    ]
