# Generated by Django 3.2.16 on 2022-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0003_auto_20221129_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
