# Generated by Django 3.2.16 on 2023-02-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_pet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_score', models.DecimalField(db_index=True, decimal_places=1, max_digits=2)),
                ('rating_score', models.DecimalField(db_index=True, decimal_places=1, max_digits=2)),
                ('overall_rank', models.DecimalField(db_index=True, decimal_places=1, max_digits=2)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_score', to='customers.provider')),
            ],
        ),
    ]
