# Generated by Django 3.2.16 on 2023-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchscore',
            name='sitter_score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
